name: monitor

on:
  schedule:
    - cron: '10,20 * * * *'

jobs:
  tesnet_bridger_roller_monitor:
    runs-on: ubuntu-latest
    steps:
      - name: check goerli
        run: |
          Commitments = `curl -X 'GET' \
          'https://indexer.auditablezk.mystiko.network/chains/5/commitments?where=%20%20%20%20%7B%0A%20%20%20%20%22status%22%3A%20%7B%22neq%22%3A%22succeeded%22%7D%0A%20%20%20%20%7D' \
          -H 'accept: application/json'`
          if [ ${{ fromJSON($Commitments.code) }} != "200" ]
          then
            echo 'get commitments from indexer meet error'
            exit 1
          fi

          if [ ${{ fromJSON($Commitments.result) }} != "[]" ]
          then
            echo 'commitment not bridge or rollup'
            exit 1
          fi

#      - name: Telegram Failure Notification
#        uses: appleboy/telegram-action@master
#        if: failure()
#        with:
#          message: ❗ Waring commitments status check error, should check bridge or roller
#          format: markdown
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
